const fs=require('fs'),assert=require('node:assert/strict'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite'),vm=require('vm');
const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync('drizzle/0000_windy_thunderball.sql','utf8'));
const env={TRACKER_OWNER_EMAIL:'owner@example.test',DB:{prepare(query){let values=[];return {bind(...v){values=v;return this},async all(){return {results:sql.prepare(query).all(...values)}},async run(){const result=sql.prepare(query).run(...values);return {meta:{changes:result.changes}}}}},async batch(statements){return Promise.all(statements.map(s=>s.run()))}}};
let user=null;
const load=(path,deps)=>{const output=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;const module={exports:{}};new Function('require','module','exports',output)(name=>{if(!(name in deps))throw Error(name);return deps[name]},module,module.exports);return module.exports;};
const seed=JSON.parse(fs.readFileSync('lib/seed.json','utf8'));
const store=load('lib/shared-store.ts',{'cloudflare:workers':{env},'./seed.json':seed});
const route=load('app/api/state/route.ts',{'cloudflare:workers':{env},'../../chatgpt-auth':{getChatGPTUser:async()=>user},'../../../lib/shared-store':store});
const request=(value,origin='https://tracker.test')=>new Request('https://tracker.test/api/state',{method:'PUT',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(value)});
(async()=>{
 let result=await (await route.GET()).json();assert.equal(result.canEdit,false);
 assert.deepEqual(JSON.parse(result.values['kpi-products']),seed.products);
 for(const kind of ['history','placementHistory'])for(const [id,rows]of Object.entries(seed[kind]))assert.deepEqual(JSON.parse(result.values[(kind==='history'?'kpi-history-':'kpi-placement-history-')+id]),rows);
 const key='kpi-history-cookbook-original',rows=JSON.parse(result.values[key]);rows.push({date:'2026-09-06',listingSales:123,keywords:{}});
 const body={key,value:JSON.stringify(rows),version:result.versions[key]};
 assert.equal((await route.PUT(request(body))).status,403);
 user={userId:'outsider',email:'viewer@example.test'};assert.equal((await route.PUT(request(body))).status,403);
 user={userId:'owner',email:'owner@example.test'};
 assert.equal((await route.GET()).status,200);
 assert.equal((await route.PUT(request(body,'https://other.test'))).status,403);
 assert.equal((await route.PUT(request({...body,value:'not-json'}))).status,400);
 assert.equal((await route.PUT(request(body))).status,200);
 assert.equal((await route.PUT(request(body))).status,409);
 result=await (await route.GET()).json();assert.deepEqual(JSON.parse(result.values[key]),rows);
 await store.ensureSeed();result=await (await route.GET()).json();assert.deepEqual(JSON.parse(result.values[key]),rows);
 const html=JSON.parse(fs.readFileSync('lib/tracker-html.ts','utf8').slice(15,-2));
 const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
 assert(html.includes('id="sharedStatus"'));assert(html.includes('id="ownerSignIn"'));assert(html.includes('body.readonly [data-edit]'));
 console.log('PASS: 326 seeded records match backup; anonymous/non-owner writes denied; CSRF denied; invalid data denied; owner save persists; stale-tab conflict detected; seeding preserves changes; embedded JS parses.');
})().catch(e=>{console.error(e);process.exitCode=1});
